<?php

/**
 * Implementation of hook_node_export_alter().
 *
 * Maintain node relationships.
 */
function node_export_relation_node_export_alter(&$nodes, $op) {
  // Currently this module only supports 'Node reference' relationships, so wrap
  // all this functionality in a check for the 'nodereference' module.   Once
  // this module handles more relationships this check should be moved down to
  // each of the function calls that contain the string 'node_reference' in the
  // function name.
  if (module_exists('nodereference')) {
     if ($op == 'export') {

       // Keyed nodes are important for preventing same node loaded again via references.
       $keyed_nodes = array();
       foreach ($nodes as $node) {
         $keyed_nodes[$node->nid] = $node;
       }

       foreach (array_keys($keyed_nodes) as $nid) {
         node_export_relation_node_reference_load($keyed_nodes, $nid);
       }

       $nodes = array_values($keyed_nodes);
     }
     elseif ($op == 'import') {
       foreach ($nodes as $node) {
         node_export_relation_node_reference_map($node->nid, $node->uuid);
       }
     }
     // Handle node insertions/updations here
     elseif ($op == 'after import') {
       // Now that all nodes are imported/updated we can restore the node referenced from UUIDS
       // NOTE: This is done because if the node referenced node is new, they we have
       // to wait for node to be saved.
       node_export_relation_node_reference_update($nodes);
     }
  }
}

/**
 * Update node references after import.
 */
function node_export_relation_node_reference_update($nodes) {
  foreach ($nodes as $node) {
    $uuid[$node->uuid] = $node->nid;
  }
  foreach ($nodes as $node) {
    $node_reference_fields = node_export_relation_node_reference_fields($node->type);
    if (!empty($node_reference_fields)) {
      foreach ($node_reference_fields as $node_reference_field) {
        if (!empty($node->$node_reference_field)) {
          foreach ($node->$node_reference_field as $key => $node_reference) {
            if (!empty($node_reference['nid'])) {
              $node_uuid = node_export_relation_node_reference_map($node_reference['nid']);
              $node->{$node_reference_field}[$key] = array('nid' => $uuid[$node_uuid]);
            }
          }
        }
      }
    }
    node_save($node);
  }
}

/**
 * Recursively load node references.
 */
function node_export_relation_node_reference_load(&$nodes, $nid) {
  // Alias for easy referencing.
  $node = &$nodes[$nid];

  // Handle uuid for the node.
  $uuid = uuid_get_uuid('node', 'nid', $node->nid);
  // Create UUID if not already created.
  if (empty($uuid)) {
    $uuid = uuid_set_uuid('node', 'nid', $node->nid);
  }

  // Get list of node reference fields for this node
  $node_reference_fields = node_export_relation_node_reference_fields($node->type);
  if (!empty($node_reference_fields)) {
    foreach ($node_reference_fields as $node_reference_field) {
      if (!empty($node->$node_reference_field)) {
        foreach ($node->$node_reference_field as $key => $node_reference) {
          if (!empty($node_reference['nid'])) {
            // Load the referenced nodes only if its not already loaded
            // This will save if from infinite loop of back references
            if (!isset($nodes[$node_reference['nid']])) {
              $new_node = node_load($node_reference['nid']);
              if (node_export_access_export($new_node)) {
                $new_node = node_export_prepare_node($new_node);
                $nodes[$new_node->nid] = $new_node;
                // Recursively load references of new nodes
                node_export_relation_node_reference_load($nodes, $new_node->nid);
              }
            }
          }
        }
      }
    }
  }
}

/**
 * Statically cache old node ids for mapping.
 */
function node_export_relation_node_reference_map($id, $uuid = NULL, $type = 'node') {
  static $map;
  if (isset($uuid)) {
    $map[$type][$id] = $uuid;
  }
  else {
    return $map[$type][$id];
  }
}

/**
 * Get an array listing the names of all node reference fields.
 *
 * @return
 *   Array of all created node reference fields.
 */
function node_export_relation_node_reference_fields($content_type_name) {
  // cache result
  static $nodereference_fields = array();

  if (empty($nodereference_fields[$content_type_name])) {
    $ct = content_types($content_type_name);
    $fields = $ct['fields'];
    if (!empty($fields)) {
      foreach ($fields as $name => $field) {
        if ($field['type'] == 'nodereference') {
          $nodereference_fields[$content_type_name][$name] = $name;
        }
      }
    }
  }

  return $nodereference_fields[$content_type_name];
}

