<?php

/**
 * @file
 * The Node export relation module.
 *
 * Helps maintain relationships between nodes during node export operations.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function node_export_relation_form_node_export_settings_alter(&$form, &$form_state, $form_id) {
  if (module_exists('node_reference')) {
    module_load_include('inc', 'node_export_relation', 'node_export_relation.node_reference');
    node_export_relation_settings_form_node_reference($form, $form_state, $form_id);
  }
}

/**
 * Implements hook_node_export_alter().
 */
function node_export_relation_node_export_alter(&$nodes, $format) {
  if (module_exists('node_reference')) {
    module_load_include('inc', 'node_export_relation', 'node_export_relation.node_reference');
    $keyed_nodes = array();
    foreach ($nodes as $node) {
      $keyed_nodes[$node->nid] = $node;
    }
    // Keyed nodes are important for preventing same node loaded again via references.
    foreach (array_keys($keyed_nodes) as $nid) {
      node_export_relation_node_reference_load($keyed_nodes, $nid);
    }
    $nodes = array_values($keyed_nodes);
  }
}

/**
 * Implements hook_node_export_import_alter().
 */
function node_export_relation_node_export_import_alter(&$nodes, $format) {
  if (module_exists('node_reference')) {
    module_load_include('inc', 'node_export_relation', 'node_export_relation.node_reference');
    foreach ($nodes as $node) {
      node_export_relation_node_reference_map($node->nid, $node->uuid);
    }
  }
}

/**
 * Implements hook_node_export_after_import_alter().
 */
function node_export_relation_node_export_after_import_alter(&$nodes, $format) {
  if (module_exists('node_reference')) {
    module_load_include('inc', 'node_export_relation', 'node_export_relation.node_reference');
    // Now that all nodes are imported/updated we can restore the node referenced from UUIDS
    // NOTE: This is done because if the node referenced node is new, they we have
    // to wait for node to be saved.
    node_export_relation_node_reference_update($nodes);
  }
}

