<?php

/**
 * @file
 * The Node export drupal 6 migrate module.
 *
 * Corrects nodes imported from Drupal 6.
 */

/**
 * Implements hook_node_export_import_alter().
 */
function node_export_d6_migrate_node_export_node_import_alter(&$node, $original_node) {
  // @todo: a better way to tell a node is from drupal 6?
  if (!is_array($node->body)) {
    node_export_d6_migrate_process_node_body($node, $original_node);
    node_export_d6_migrate_process_node_cck($node, $original_node);
    node_export_d6_migrate_process_node_taxonomy($node, $original_node);
  }
}

/**
 * Migrate the body field.
 *
 * The code in this function is based on node_update_7006().
 */
function node_export_d6_migrate_process_node_body(&$node, $original_node) {
  // Used below when updating the stored text format of each node body.
  $sandbox['existing_text_formats'] = db_query("SELECT format FROM {filter_format}")->fetchCol();

  $langcode = empty($original_node->language) ? LANGUAGE_NONE : $original_node->language;

  $node->body = array(
    $langcode => array(
      "0" => array(),
    )
  );

  if (!empty($original_node->teaser) && $original_node->teaser != text_summary($original_node->body)) {
    $node->body[$langcode][0]['summary'] = $original_node->teaser;
  }

  // Do this after text_summary() above.
  $break = '<!--break-->';
  if (substr($original_node->body, 0, strlen($break)) == $break) {
    $original_node->body = substr($original_node->body, strlen($break));
  }
  $node->body[$langcode][0]['value'] = $original_node->body;

  if (empty($original_node->body) && empty($original_node->format)) {
    $node->body[$langcode][0]['format'] = NULL;
  }
  elseif (!in_array($original_node->format, $sandbox['existing_text_formats'])) {
    $node->body[$langcode][0]['format'] = variable_get('filter_default_format', 1);
  }
  else {
    $node->body[$langcode][0]['format'] = $original_node->format;
  }
}

/**
 * Migrate CCK data.
 */
function node_export_d6_migrate_process_node_cck(&$node, $original_node) {
  if (module_exists('content')) {
    // @todo
  }
}

/**
 * Migrate taxonomy data.
 */
function node_export_d6_migrate_process_node_taxonomy(&$node, $original_node) {
  if (module_exists('taxonomy')) {
    // @todo
  }
}