<?php

/**
 * @file
 * The Node export Drupal module.
 *
 * Adds Drupal var export format to Node export.
 */

/**
 * Implements hook_node_export_format_handlers().
 */
function node_export_drupal_node_export_format_handlers() {
  return array(
    'drupal' => array(
      '#title' => t('Drupal var export'),
      '#module' => 'node_export_drupal',
      '#description' => t(
        '<a href="!drupal">Drupal var export</a> code.',
        array(
          '!drupal' => 'http://api.drupal.org/api/drupal/includes!utility.inc/function/drupal_var_export/7'
        )
      ),
    ),
  );
}

/**
 * Implements hook_node_export().
 */
function node_export_drupal_node_export($nodes, $format) {
  require_once DRUPAL_ROOT . '/includes/utility.inc';
  return drupal_var_export($nodes);
}

/**
 * Implements hook_node_export_import().
 */
function node_export_drupal_node_export_import($code_string) {
  return eval('return ' . $code_string . ';');
}
